admin/base/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from settings import ADMIN_BASE

from . import views

base_pattern = '^{}'.format(ADMIN_BASE)

urlpatterns = [
    ### ADMIN ###
    url(
        base_pattern,
        include([
            url(r'^$', views.home, name='home'),
            url(r'^admin/', admin.site.urls),
            url(r'^spam/', include('admin.spam.urls', namespace='spam')),
            url(r'^institutions/', include('admin.institutions.urls', namespace='institutions')),
            url(r'^preprint_providers/', include('admin.preprint_providers.urls', namespace='preprint_providers')),
            url(r'^account/', include('admin.common_auth.urls', namespace='auth')),
            url(r'^password/', include('password_reset.urls')),
            url(r'^nodes/', include('admin.nodes.urls', namespace='nodes')),
            url(r'^preprints/', include('admin.preprints.urls', namespace='preprints')),
            url(r'^subjects/', include('admin.subjects.urls', namespace='subjects')),
            url(r'^users/', include('admin.users.urls', namespace='users')),
            url(r'^meetings/', include('admin.meetings.urls',
                                       namespace='meetings')),
            url(r'^project/', include('admin.pre_reg.urls', namespace='pre_reg')),
            url(r'^metrics/', include('admin.metrics.urls',
                                      namespace='metrics')),
            url(r'^desk/', include('admin.desk.urls',
                                   namespace='desk')),
        ]),
    ),
]

admin.site.site_header = 'OSF-Admin administration'

admin/pre_reg/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as login

from admin.pre_reg import views

app_name = 'admin'

urlpatterns = [
    url(r'^$', views.DraftListView.as_view(), name='prereg'),
    url(r'^checkout_checkup/$', views.CheckoutCheckupView.as_view(), name='checkout_checkup'),
    url(
        r'^drafts/(?P<draft_pk>[0-9a-z]+)/$',
        views.DraftDetailView.as_view(),
        name='view_draft'
    ),
    url(
        r'^drafts/(?P<draft_pk>[0-9a-z]+)/update/$',
        views.DraftFormView.as_view(),
        name='update_draft'
    ),
    url(
        r'^drafts/(?P<draft_pk>[0-9a-z]+)/comment/$',
        views.CommentUpdateView.as_view(),
        name='comment'
    ),
    url(
        r'^(?P<node_id>[a-zA-Z0-9]{5})/files/(?P<provider>.+?)/(?P<file_id>.+)/?',
        login(views.view_file),
        name='view_file'
    )
]

api/base/urls.py
from django.conf import settings as drf_settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from . import views
from . import settings
from . import versioning

default_version = versioning.decimal_version_to_url_path(settings.REST_FRAMEWORK['DEFAULT_VERSION'])

# Please keep URLs alphabetized for auto-generated documentation
urlpatterns = [
    url('^(?P<version>(v2))/',
        include(
            [
                url(r'^$', views.root, name='root'),
                url(r'^status/', views.status_check, name='status_check'),
                url(r'^actions/', include('api.actions.urls', namespace='actions')),
                url(r'^addons/', include('api.addons.urls', namespace='addons')),
                url(r'^applications/', include('api.applications.urls', namespace='applications')),
                url(r'^citations/', include('api.citations.urls', namespace='citations')),
                url(r'^collections/', include('api.collections.urls', namespace='collections')),
                url(r'^comments/', include('api.comments.urls', namespace='comments')),
                url(r'^docs/', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version}),
                url(r'^files/', include('api.files.urls', namespace='files')),
                url(r'^guids/', include('api.guids.urls', namespace='guids')),
                url(r'^identifiers/', include('api.identifiers.urls', namespace='identifiers')),
                url(r'^institutions/', include('api.institutions.urls', namespace='institutions')),
                url(r'^licenses/', include('api.licenses.urls', namespace='licenses')),
                url(r'^logs/', include('api.logs.urls', namespace='logs')),
                url(r'^metaschemas/', include('api.metaschemas.urls', namespace='metaschemas')),
                url(r'^nodes/', include('api.nodes.urls', namespace='nodes')),
                url(r'^preprints/', include('api.preprints.urls', namespace='preprints')),
                url(r'^preprint_providers/', include('api.preprint_providers.urls', namespace='preprint_providers')),
                url(r'^registrations/', include('api.registrations.urls', namespace='registrations')),
                url(r'^search/', include('api.search.urls', namespace='search')),
                url(r'^taxonomies/', include('api.taxonomies.urls', namespace='taxonomies')),
                url(r'^test/', include('api.test.urls', namespace='test')),
                url(r'^tokens/', include('api.tokens.urls', namespace='tokens')),
                url(r'^users/', include('api.users.urls', namespace='users')),
                url(r'^view_only_links/', include('api.view_only_links.urls', namespace='view-only-links')),
                url(r'^wikis/', include('api.wikis.urls', namespace='wikis')),
            ],
        )
        ),
    url(r'^$', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version})
]


urlpatterns += static('/static/', document_root=drf_settings.STATIC_ROOT)

handler404 = views.error_404

admin/pre_reg/forms.py
from django import forms


class DraftRegistrationForm(forms.Form):

    proof_of_publication = forms.ChoiceField(
        label='Proof of publication',
        choices=(
            ('not_submitted', 'Published Article Not Yet Submitted'),
            ('submitted', 'Published Article Submitted'),
            ('under_review', 'Published Article Under Review'),
            ('approved', 'Published Article Approved'),
            ('rejected', 'Published Article Rejected'),
        )
    )
    payment_sent = forms.BooleanField(
        label='Payment sent',
        required=False
    )
    assignee = forms.ChoiceField(
        label='Assignee',
        choices=list(),
        required=False,
    )

    notes = forms.CharField(
        label='Notes',
        widget=forms.Textarea(
            attrs={
                'class': 'prereg-form-notes'
            }
        ),
        required=False
    )

    approve_reject = forms.ChoiceField(
        label='Action',
        choices=(
            ('approve', 'Approve'),
            ('reject', 'Reject'),
        ),
        required=False,
        widget=forms.RadioSelect(),
    )

    def __init__(self, *args, **kwargs):
        prereg_reviewers = ((None, 'None'), )
        self.base_fields['assignee'] = forms.ChoiceField(
            choices=prereg_reviewers, required=False)
        super(DraftRegistrationForm, self).__init__(*args, **kwargs)

admin/pre_reg/views.py
from __future__ import unicode_literals

import json

from django.views.generic import ListView, DeleteView, DetailView, FormView, UpdateView
from django.views.defaults import permission_denied, bad_request
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.urlresolvers import reverse
from django.http import JsonResponse, Http404
from django.shortcuts import redirect

from osf.models.admin_log_entry import (
    update_admin_log,
    ACCEPT_PREREG,
    REJECT_PREREG,
    COMMENT_PREREG,
    CHECKOUT_CHECKUP,
)

from admin.pre_reg import serializers
from admin.pre_reg.forms import DraftRegistrationForm
from framework.exceptions import PermissionsError
from website.exceptions import NodeStateError

from osf.models import (
    BaseFileNode,
    DraftRegistration,
    MetaSchema,
    Node,
    OSFUser,
)
from website.project.metadata.schemas import from_json
from website.prereg.utils import get_prereg_schema


SORT_BY = {
    'initiator': 'initiator__fullname',
    'n_initiator': '-initiator__fullname',
    'title': 'branched_from__title',
    'n_title': '-branched_from__title',
    'date': 'approval__initiation_date',
    'n_date': '-approval__initiation_date',
    'state': 'approval__state',
    'n_state': '-approval__state',
}


class DraftListView(PermissionRequiredMixin, ListView):
    template_name = 'pre_reg/draft_list.html'
    ordering = '-approval__initiation_date'
    context_object_name = 'draft'
    permission_required = 'osf.view_prereg'
    raise_exception = True

    def get_queryset(self):
        return DraftRegistration.objects.filter(
            registration_schema=get_prereg_schema(),
        ).exclude(
            approval__isnull=True,
            registered_node__isnull=True,
        ).order_by(self.get_ordering())

    def get_context_data(self, **kwargs):
        query_set = kwargs.pop('object_list', self.object_list)
        page_size = self.get_paginate_by(query_set)
        paginator, page, query_set, is_paginated = self.paginate_queryset(
            query_set, page_size)
        return {
            'drafts': [
                serializers.serialize_draft_registration(d, json_safe=False)
                for d in query_set
            ],
            'page': page,
            'p': self.get_paginate_by(query_set),
            'SORT_BY': SORT_BY,
            'order': self.get_ordering(),
            'status': self.request.GET.get('status', 'all'),
        }

    def get_paginate_by(self, queryset):
        return int(self.request.GET.get('p', 10))

    def get_paginate_orphans(self):
        return int(self.get_paginate_by(None) / 11.0) + 1

    def get_ordering(self):
        return self.request.GET.get('order_by', self.ordering)


class CheckoutCheckupView(PermissionRequiredMixin, DeleteView):
    """ View for button that checks status of all prereg drafts and removes checkouts that lingered beyond approval/rejection"""
    template_name = 'pre_reg/checkout_checkup.html'
    permission_required = 'osf.view_prereg'
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = {}
        context.setdefault('bad_drafts_count', str(self.get_object().count()))
        return super(CheckoutCheckupView, self).get_context_data(**context)

    def get_object(self, queryset=None):
        self.prereg_admins = OSFUser.objects.filter(groups__name='prereg_view')
        self.bad_drafts = DraftRegistration.objects.filter(
            registration_schema=MetaSchema.objects.get(name='Prereg Challenge', schema_version=2),
            approval__state__in=['approved', 'rejected'],
            branched_from__files__checkout__in=self.prereg_admins
        ).distinct().values_list('id', flat=True)
        return self.bad_drafts

    def delete(self, request, *args, **kwargs):
        if not self.get('bad_drafts', None):
            self.get_object()

        for draft_id in self.bad_drafts:
            draft = DraftRegistration.objects.get(id=draft_id)
            for draft_file in draft.branched_from.files.filter(checkout__in=self.prereg_admins):
                draft_file.checkout = None
                draft_file.save()

            update_admin_log(
                user_id=self.request.user.id,
                object_id=draft.branched_from._id,
                object_repr='Node',
                message='Cleared Prereg checkouts from {}'.format(draft.branched_from._id),
                action_flag=CHECKOUT_CHECKUP
            )
        return redirect(reverse('pre_reg:prereg'))


class DraftDetailView(PermissionRequiredMixin, DetailView):
    template_name = 'pre_reg/draft_detail.html'
    context_object_name = 'draft'
    permission_required = 'osf.view_prereg'
    raise_exception = True

    def get_object(self, queryset=None):
        draft = DraftRegistration.objects.select_related('approval').get(_id=self.kwargs.get('draft_pk'))
        self.checkout_files(draft)
        try:
            return serializers.serialize_draft_registration(draft)
        except AttributeError:
            raise Http404('{} with id "{}" not found.'.format(
                self.context_object_name.title(),
                self.kwargs.get('draft_pk')
            ))

    def checkout_files(self, draft):
        # Do not check out files if rejected or approved
        if not draft.approval or draft.approval.state == 'unapproved':
            prereg_user = self.request.user
            for item in get_metadata_files(draft):
                item.checkout = prereg_user
                item.save()


class DraftFormView(PermissionRequiredMixin, FormView):
    template_name = 'pre_reg/draft_form.html'
    form_class = DraftRegistrationForm
    context_object_name = 'draft'
    permission_required = 'osf.view_prereg'
    raise_exception = True

    def dispatch(self, request, *args, **kwargs):
        self.draft = DraftRegistration.load(self.kwargs.get('draft_pk'))
        if self.draft is None:
            raise Http404('{} with id "{}" not found.'.format(
                self.context_object_name.title(),
                self.kwargs.get('draft_pk')
            ))
        return super(DraftFormView, self).dispatch(request, *args, **kwargs)

    def get_initial(self):
        flags = self.draft.flags
        self.initial = {
            'notes': self.draft.notes,
            'assignee': flags.get('assignee'),
            'payment_sent': flags.get('payment_sent'),
            'proof_of_publication': flags.get('proof_of_publication'),
        }
        return super(DraftFormView, self).get_initial()

    def get_context_data(self, **kwargs):
        kwargs.setdefault('draft', serializers.serialize_draft_registration(
            self.draft,
            json_safe=False
        ))
        kwargs.setdefault('IMMEDIATE', serializers.IMMEDIATE)
        return super(DraftFormView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        if 'approve_reject' in form.changed_data:
            osf_user = self.request.user
            try:
                if form.cleaned_data.get('approve_reject') == 'approve':
                    flag = ACCEPT_PREREG
                    message = 'Approved'
                    self.draft.approve(osf_user)
                else:
                    flag = REJECT_PREREG
                    message = 'Rejected'
                    self.draft.reject(osf_user)
            except PermissionsError as e:
                return permission_denied(self.request, e)
            self.checkin_files(self.draft)
            update_admin_log(self.request.user.id, self.kwargs.get('draft_pk'),
                             'Draft Registration', message, flag)
        admin_settings = form.cleaned_data
        self.draft.notes = admin_settings.get('notes', self.draft.notes)
        del admin_settings['approve_reject']
        del admin_settings['notes']
        self.draft.flags = admin_settings
        self.draft.save()
        return super(DraftFormView, self).form_valid(form)

    def checkin_files(self, draft):
        for item in get_metadata_files(draft):
            item.checkout = None
            item.save()

    def get_success_url(self):
        return '{}?page={}'.format(reverse('pre_reg:prereg'),
                                   self.request.POST.get('page', 1))


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    context_object_name = 'draft'
    permission_required = ('osf.view_prereg', 'osf.administer_prereg')
    raise_exception = True

    def get_object(self, *args, **kwargs):
        return DraftRegistration.load(self.kwargs.get('draft_pk'))

    def post(self, request, *args, **kwargs):
        try:
            data = json.loads(request.body).get('schema_data', {})
            draft = DraftRegistration.load(self.kwargs.get('draft_pk'))
            draft.update_metadata(data)
            draft.save()
            log_message = list()
            for key, value in data.iteritems():
                comments = data.get(key, {}).get('comments', [])
                for comment in comments:
                    log_message.append('{}: {}'.format(key, comment['value']))
            update_admin_log(
                user_id=request.user.id,
                object_id=draft._id,
                object_repr='Draft Registration',
                message='Comments: <p>{}</p>'.format('</p><p>'.join(log_message)),
                action_flag=COMMENT_PREREG
            )
            return JsonResponse(serializers.serialize_draft_registration(draft))
        except AttributeError:
            raise Http404('{} with id "{}" not found.'.format(
                self.context_object_name.title(),
                self.kwargs.get('draft_pk')
            ))
        except NodeStateError as e:
            return bad_request(request, e)


def view_file(request, node_id, provider, file_id):
    fp = BaseFileNode.load(file_id)
    wb_url = fp.generate_waterbutler_url()
    return redirect(wb_url)


def get_metadata_files(draft):

admin/templates/pre_reg/checkout_checkup.html
<form class="well" method="post" action="{% url 'pre_reg:checkout_checkup' %}">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Total nodes with bad checkouts: {{ bad_drafts_count }}</h3>
        <p><b>Instructions:</b></p>
        <p>The above number indicates the number of nodes with lingering pre reg checkouts.</p>
        <p>Clicking "Confirm" will load up each of these nodes and remove these bad checkouts.</p>
        <p>Running this may take a minute.</p>
        <p>If the number is large (>10) do not run during peak hours.</p>
        
        <p>Click the "Checkout Checkup" button again to confirm the number dropped to 0.</p>
    </div>
    {% csrf_token %}
    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Confirm" />
        <button type="button" class="btn btn-default" data-dismiss="modal">
            Cancel
        </button>
    </div>
</form>

admin/templates/pre_reg/draft_detail.html
{% extends 'base.html' %}
{% load render_bundle from webpack_loader %}
{% load staticfiles %}
{% load filters %}

{% block title %}
<title>OSF Admin | {{ draft.title }}</title>
{% endblock %}

{% block content %}
{% render_bundle 'vendor' %}
<link href="{% static 'css/registrations.css' %}" rel="stylesheet" type="text/css" />
<script type="application/javascript">
    window.contextVars = window.contextVars || {};
    window.contextVars.currentUser = {
        id: -1,
        fullname: 'Prereg Admin'
    };
    window.contextVars.draft = {{ draft | jsonify | safe }};
    window.contextVars.urls = {
        updateDraft: '{% url 'pre_reg:comment' draft.pk %}'
    };
    // Grab csrf_token
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('admin-csrf');
    function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
</script>

<div class="container-fluid scripted" id="draftRegistrationScope">
    <div class="row">
        <div class="col-md-9 col-sm-9">
            <h3>Review draft submission</h3>
        </div>
        <div class="col-md-3 col-sm-3">
            <h5>Last saved: <span data-bind="text: $root.lastSaved"></span></h5>
        </div>
    </div>
    <hr />
  <div class="row">
    <div class="col-md-12">
      <div id="registrationEditorScope">
        <div class="container">
          <div class="row-fluid">
            <div class="span2 col-md-2 columns eight large-8">
              <ul class="nav nav-stacked list-group" data-bind="foreach: {data: pages, as: 'page'}, visible: pages().length > 1">
                <li class="re-navbar">
                  <a class="registration-editor-page" id="top-nav" style="text-align: left;" data-bind="text: title, click: $root.selectPage.bind($root), style:{'font-weight': active() ? 'bold' : 'normal'}">
                    <i class="fa fa-caret-right"></i>
                  </a>
                </li>
              </ul>
            </div>
            <div class="span10 col-md-8 col-sm-10 columns eight large-8">
              <!-- EDITOR -->
              <div data-bind="if: currentPage">
                <div data-bind="foreach: {data: currentPage().questions, as: 'question'}">
                  <div class="row">
                    <strong data-bind="attr: {id: question.id}, text: question.title"></strong>:
                    <div class="well">
                      <p>
                        <span data-bind="previewQuestion: $root.context(question, $root, true)"></span>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="well col-md-10" data-bind="template: {data: currentPage, name: 'commentable'}"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="row" data-bind="ifnot: onLastPage">
        <a data-bind="click: nextPage" class="btn btn-primary">Next Page</a>
    </div>
</div>
    {% if perms.osf.administer_prereg %}
        {% include "pre_reg/comment_editor.html" %}
    {% endif %}
{% endblock %}

{% block bottom_js %}
  {% render_bundle 'admin-registration-edit-page' %}
{% endblock %}

admin/templates/pre_reg/draft_form.html
<form action="{% url 'pre_reg:update_draft' draft.pk %}"
      class="well" method="post">
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">x</button>
    <h4>Draft info form for: <strong>{{ draft.title }}</strong></h4>
</div>
<div class="modal-body">
<div class="container">
    <div class="row">
    <h4 style="margin-top: 0px">
    {% if draft.is_pending_approval %}
    <span class="label label-warning">Pending Approval</span>
    {% elif draft.is_approved %}
    <span class="label label-lg label-success">Approved</span>
    {% elif draft.is_rejected %}
    <span class="label label-lg label-danger">Rejected</span>
    {% endif %}
    </h4>
    </div>

    <div class="row">
        <span class="text-muted"> Applicant </span>
        <strong> {{ draft.initiator.full_name }}</strong>
        submitted on <strong>{{ draft.submitted | date:"N dS" }}</strong>
        at <strong>{{draft.submitted | date:"g:i a" }}</strong>
    </div>

    <div class="row">
    <a href="mailto:{{ draft.initiator.username }}">{{ draft.initiator.username }} </a>
    </div>

    <div class="row">Embargo release:
        {% if draft.embargo == IMMEDIATE %}
            <strong>{{ draft.embargo | capfirst }}</strong>
        {% else %}
            <strong>{{ draft.embargo | date:"N dS Y" }}</strong>
            at <strong>{{draft.embargo | date:"g:i a" }}</strong>
        {%  endif %}
    </div>

    <div class="row">
        {% if draft.registered_node %}
            <a href="{{ draft.registered_node }}">
                {{ draft.registered_node }}
            </a>
        {% else %}
            None
        {% endif %}
    </div>
    <br>
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            <span style="color:red">{{ field.errors }}</span>
            {{ field.label_tag }}
            {% if field.label == 'Action' %}
                {% if draft.is_approved or draft.is_rejected %}
                    --
                {% else %}
                <div class="btn-group" data-toggle="buttons">
                    {% for choice in field %}
                        {{ choice.id }}
                    {% if forloop.counter0 %}
                        <label class="btn btn-danger">
                    {% else %}
                        <label class="btn btn-success">
                    {% endif %}
                        <input type="radio" id="{{ choice.id_for_label }}" autocomplete="off">{{ choice.choice_label }}{{ choice.tag }}
                    </label>
                    {% endfor %}
                </div>
                {% endif %}
            {% else %}
                {{ field }}
            {% endif %}
        </div>
    {% endfor %}
    <div class="row">
        <strong><h4>Logs</h4></strong>
    </div>
    {% for log in draft.logs %}
        <div class="row">
            {{ log }}
        </div>
    {% empty %}
        <div class="row">
            None: draft existed before logs.
        </div>
    {% endfor %}
</div>
</div>
<div class="modal-footer">
    <input type="hidden" name="page" value="{{ page_number }}" />
    <input type="submit" class="btn btn-primary" value="Save"
           onclick="this.disabled=true;this.value='Sending, please wait...';this.form.submit();"/>
    <button type="button" class="btn btn-default"
            data-dismiss="modal">
        Cancel
    </button>
</div>
</form>

admin/templates/pre_reg/draft_list.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load prereg_extras %}

{% load static %}
{% block title %}
    <title>OSF Admin | Prereg</title>
{% endblock %}

{% block content %}
    <h2>List of Preregistration Drafts</h2>
    {% if perms.osf.view_prereg %}
    <div>
        {# Add types here #}
        <span>
            <a href="{% url 'pre_reg:checkout_checkup' %}"
                data-toggle="modal" data-target="#confirmCheckoutCheckup"
                class="btn btn-default">
            Checkout Checkup
            </a>
        </span>
        <div class="modal" id="confirmCheckoutCheckup">
            <div class="modal-dialog">
                <div class="modal-content"></div>
                {# Data from above link #}
            </div>
        </div>
    </div>
    {%  endif %}
    {% include "util/pagination.html" with items=page status=status pagin=p order=order %}
    <table class="table table-striped table-hover table-responsive">
    <thead>
        <tr>
            <th>
                Status
                <a href="{% reverse_list p=p order_by=SORT_BY.state status=status page=page.number %}"
                   class="caret"></a>
                <span class="dropup">
                <a href="{% reverse_list p=p order_by=SORT_BY.n_state status=status page=page.number %}"
                   class="caret"></a>
                </span>
            </th>
            <th>
                Title
                <a href="{% reverse_list p=p order_by=SORT_BY.title status=status page=page.number %}"
                   class="caret"></a>
                <span class="dropup">
                <a href="{% reverse_list p=p order_by=SORT_BY.n_title status=status page=page.number %}"
                   class="caret"></a>
                </span>
            </th>
            <th>
                Applicant
                <a href="{% reverse_list p=p order_by=SORT_BY.initiator status=status page=page.number %}"
                   class="caret"></a>
                <span class="dropup">
                <a href="{% reverse_list p=p order_by=SORT_BY.n_initiator status=status page=page.number %}"
                   class="caret"></a>
                </span>
            </th>
            <th>
                Date submitted
                <a href="{% reverse_list p=p order_by=SORT_BY.date status=status page=page.number %}"
                   class="caret"></a>
                <span class="dropup">
                <a href="{% reverse_list p=p order_by=SORT_BY.n_date status=status page=page.number %}"
                   class="caret"></a>
                </span>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for draft in drafts %}
    <tr>
        <td>
            <h4 style="margin-top: 0px">
            {% if draft.is_pending_approval %}
            <span class="label label-warning">
            {% elif draft.is_approved %}
                {% if 'but' in draft.status %}
                    <span class="label label-lg label-default">
                {% else %}
                    <span class="label label-lg label-success">
                {% endif %}
            {% elif draft.is_rejected %}
            <span class="label label-lg label-danger">
            {% endif %}
                {{ draft.status }}</span>
            </h4>
        </td>
        <td>
            {{ draft.title|truncatechars:40 }}
        </td>
        <td>
            {{ draft.initiator.full_name }}
        </td>
        <td>
            {{ draft.submitted | date:"N dS Y g:i a"}}
        </td>
        <td>
            {% if perms.osf.administer_prereg %}
            <a href="{% url 'pre_reg:update_draft' draft.pk %}"
               class="btn btn-success" data-toggle="modal"
               data-target="#form{{ draft.pk }}">
                View details
            </a>
            <div class="modal" id="form{{ draft.pk }}">
                <div class="modal-dialog">
                    <div class="modal-content">
                        {# Data from above link #}
                    </div>
                </div>
            </div>
            {%  endif %}
            <a href="{% url 'pre_reg:view_draft' draft.pk %}" target="_blank"
               class="btn btn-primary">
                View Draft
            </a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}