admin/nodes/urls.py
from django.conf.urls import url
from admin.nodes import views

app_name = 'admin'

urlpatterns = [
    url(r'^$', views.NodeFormView.as_view(),
        name='search'),
    url(r'^flagged_spam$', views.NodeFlaggedSpamList.as_view(),
        name='flagged-spam'),
    url(r'^known_spam$', views.NodeKnownSpamList.as_view(),
        name='known-spam'),
    url(r'^known_ham$', views.NodeKnownHamList.as_view(),
        name='known-ham'),
    url(r'^(?P<guid>[a-z0-9]+)/$', views.NodeView.as_view(),
        name='node'),
    url(r'^(?P<guid>[a-z0-9]+)/logs/$', views.AdminNodeLogView.as_view(),
        name='node-logs'),
    url(r'^registration_list/$', views.RegistrationListView.as_view(),
        name='registrations'),
    url(r'^(?P<guid>[a-z0-9]+)/update_embargo/$',
        views.RegistrationUpdateEmbargoView.as_view(), name='update_embargo'),
    url(r'^(?P<guid>[a-z0-9]+)/remove/$', views.NodeDeleteView.as_view(),
        name='remove'),
    url(r'^(?P<guid>[a-z0-9]+)/restore/$', views.NodeDeleteView.as_view(),
        name='restore'),
    url(r'^(?P<guid>[a-z0-9]+)/confirm_spam/$', views.NodeConfirmSpamView.as_view(),
        name='confirm-spam'),
    url(r'^(?P<guid>[a-z0-9]+)/confirm_ham/$', views.NodeConfirmHamView.as_view(),
        name='confirm-ham'),
    url(r'^(?P<guid>[a-z0-9]+)/reindex_share_node/$', views.NodeReindexShare.as_view(),
        name='reindex-share-node'),
    url(r'^(?P<guid>[a-z0-9]+)/reindex_elastic_node/$', views.NodeReindexElastic.as_view(),
        name='reindex-elastic-node'),
    url(r'^(?P<node_id>[a-z0-9]+)/remove_user/(?P<user_id>[a-z0-9]+)/$',
        views.NodeRemoveContributorView.as_view(), name='remove_user'),
]

admin/preprints/urls.py
from django.conf.urls import url
from admin.preprints import views

app_name = 'admin'

urlpatterns = [
    url(r'^$', views.PreprintFormView.as_view(), name='search'),
    url(r'^(?P<guid>[a-z0-9]+)/$', views.PreprintView.as_view(), name='preprint'),
    url(r'^(?P<guid>[a-z0-9]+)/reindex_share_preprint/$', views.PreprintReindexShare.as_view(),
        name='reindex-share-preprint'),
]

api/base/urls.py
from django.conf import settings as drf_settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from . import views
from . import settings
from . import versioning

default_version = versioning.decimal_version_to_url_path(settings.REST_FRAMEWORK['DEFAULT_VERSION'])

# Please keep URLs alphabetized for auto-generated documentation
urlpatterns = [
    url('^(?P<version>(v2))/',
        include(
            [
                url(r'^$', views.root, name='root'),
                url(r'^status/', views.status_check, name='status_check'),
                url(r'^actions/', include('api.actions.urls', namespace='actions')),
                url(r'^addons/', include('api.addons.urls', namespace='addons')),
                url(r'^applications/', include('api.applications.urls', namespace='applications')),
                url(r'^citations/', include('api.citations.urls', namespace='citations')),
                url(r'^collections/', include('api.collections.urls', namespace='collections')),
                url(r'^comments/', include('api.comments.urls', namespace='comments')),
                url(r'^docs/', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version}),
                url(r'^files/', include('api.files.urls', namespace='files')),
                url(r'^guids/', include('api.guids.urls', namespace='guids')),
                url(r'^identifiers/', include('api.identifiers.urls', namespace='identifiers')),
                url(r'^institutions/', include('api.institutions.urls', namespace='institutions')),
                url(r'^licenses/', include('api.licenses.urls', namespace='licenses')),
                url(r'^logs/', include('api.logs.urls', namespace='logs')),
                url(r'^metaschemas/', include('api.metaschemas.urls', namespace='metaschemas')),
                url(r'^nodes/', include('api.nodes.urls', namespace='nodes')),
                url(r'^preprints/', include('api.preprints.urls', namespace='preprints')),
                url(r'^preprint_providers/', include('api.preprint_providers.urls', namespace='preprint_providers')),
                url(r'^registrations/', include('api.registrations.urls', namespace='registrations')),
                url(r'^search/', include('api.search.urls', namespace='search')),
                url(r'^taxonomies/', include('api.taxonomies.urls', namespace='taxonomies')),
                url(r'^test/', include('api.test.urls', namespace='test')),
                url(r'^tokens/', include('api.tokens.urls', namespace='tokens')),
                url(r'^users/', include('api.users.urls', namespace='users')),
                url(r'^view_only_links/', include('api.view_only_links.urls', namespace='view-only-links')),
                url(r'^wikis/', include('api.wikis.urls', namespace='wikis')),
            ],
        )
        ),
    url(r'^$', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version})
]


urlpatterns += static('/static/', document_root=drf_settings.STATIC_ROOT)

handler404 = views.error_404

api/preprints/urls.py
from django.conf.urls import url

from . import views

app_name = 'osf'

urlpatterns = [
    url(r'^$', views.PreprintList.as_view(), name=views.PreprintList.view_name),
    url(r'^(?P<preprint_id>\w+)/$', views.PreprintDetail.as_view(), name=views.PreprintDetail.view_name),
    url(r'^(?P<preprint_id>\w+)/citation/$', views.PreprintCitationDetail.as_view(), name=views.PreprintCitationDetail.view_name),
    url(r'^(?P<preprint_id>\w+)/citation/(?P<style_id>[-\w]+)/$', views.PreprintCitationStyleDetail.as_view(), name=views.PreprintCitationStyleDetail.view_name),
    url(r'^(?P<preprint_id>\w+)/identifiers/$', views.PreprintIdentifierList.as_view(), name=views.PreprintIdentifierList.view_name),
    url(r'^(?P<preprint_id>\w+)/contributors/$', views.PreprintContributorsList.as_view(), name=views.PreprintContributorsList.view_name),
    url(r'^(?P<preprint_id>\w+)/actions/$', views.PreprintActionList.as_view(), name=views.PreprintActionList.view_name),
]

api/search/urls.py
from django.conf.urls import url

from api.search import views

app_name = 'osf'

urlpatterns = [
    url(r'^$', views.Search.as_view(), name=views.Search.view_name),
    url(r'^components/$', views.SearchComponents.as_view(), name=views.SearchComponents.view_name),
    url(r'^files/$', views.SearchFiles.as_view(), name=views.SearchFiles.view_name),
    url(r'^projects/$', views.SearchProjects.as_view(), name=views.SearchProjects.view_name),
    url(r'^registrations/$', views.SearchRegistrations.as_view(), name=views.SearchRegistrations.view_name),
    url(r'^users/$', views.SearchUsers.as_view(), name=views.SearchUsers.view_name),
    url(r'^institutions/$', views.SearchInstitutions.as_view(), name=views.SearchInstitutions.view_name),

    # not currently supported by v1, but should be supported by v2
    # url(r'^nodes/$', views.SearchProjects.as_view(), name=views.SearchProjects.view_name),
]

admin/preprints/forms.py
from django import forms

from osf.models import PreprintService


class ChangeProviderForm(forms.ModelForm):
    class Meta:
        model = PreprintService
        fields = ('provider',)

admin/preprints/views.py
from __future__ import unicode_literals

from django.views.generic import UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect

from osf.models.preprint_service import PreprintService
from osf.models.admin_log_entry import update_admin_log, REINDEX_SHARE
from website.preprints.tasks import update_preprint_share

from framework.exceptions import PermissionsError
from admin.base.views import GuidFormView, GuidView
from admin.nodes.templatetags.node_extras import reverse_preprint
from admin.preprints.serializers import serialize_preprint
from admin.preprints.forms import ChangeProviderForm


class PreprintFormView(PermissionRequiredMixin, GuidFormView):
    """ Allow authorized admin user to input specific preprint guid.

    Basic form. No admin models.
    """
    template_name = 'preprints/search.html'
    object_type = 'preprint'
    permission_required = 'osf.view_preprintservice'
    raise_exception = True

    @property
    def success_url(self):
        return reverse_preprint(self.guid)


class PreprintView(PermissionRequiredMixin, UpdateView, GuidView):
    """ Allow authorized admin user to view preprints

    View of OSF database. No admin models.
    """
    template_name = 'preprints/preprint.html'
    context_object_name = 'preprintservice'
    permission_required = 'osf.view_preprintservice'
    raise_exception = True
    form_class = ChangeProviderForm

    def get_success_url(self):
        return reverse_lazy('preprints:preprint', kwargs={'guid': self.kwargs.get('guid')})

    def post(self, request, *args, **kwargs):
        if not request.user.has_perm('osf.change_preprintservice'):
            raise PermissionsError("This user does not have permission to update this preprint's provider.")
        return super(PreprintView, self).post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return PreprintService.load(self.kwargs.get('guid'))

    def get_context_data(self, **kwargs):
        preprint = PreprintService.load(self.kwargs.get('guid'))
        # TODO - we shouldn't need this serialized_preprint value -- https://openscience.atlassian.net/browse/OSF-7743
        kwargs['serialized_preprint'] = serialize_preprint(preprint)
        kwargs['change_provider_form'] = ChangeProviderForm(instance=preprint)
        return super(PreprintView, self).get_context_data(**kwargs)


class PreprintReindexShare(PermissionRequiredMixin, DeleteView):
    template_name = 'preprints/reindex_preprint_share.html'
    context_object_name = 'preprintservice'
    object = None
    permission_required = 'osf.view_preprintservice'
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = {}
        context.setdefault('guid', kwargs.get('object')._id)
        return super(PreprintReindexShare, self).get_context_data(**context)

    def get_object(self, queryset=None):
        return PreprintService.load(self.kwargs.get('guid'))

    def delete(self, request, *args, **kwargs):
        preprint = self.get_object()
        update_preprint_share(preprint)
        update_admin_log(
            user_id=self.request.user.id,
            object_id=preprint._id,
            object_repr='Preprint',
            message='Preprint Reindexed (SHARE): {}'.format(preprint._id),
            action_flag=REINDEX_SHARE
        )
        return redirect(reverse_preprint(self.kwargs.get('guid')))

api_tests/preprints/views/test_preprint_actions.py
import pytest

from api.base.settings.defaults import API_BASE
from osf_tests.factories import (
    PreprintFactory,
    AuthUserFactory,
)
from reviews.permissions import GroupHelper
from website.util import permissions as osf_permissions

from api_tests.reviews.mixins.filter_mixins import ActionFilterMixin
from api_tests.reviews.mixins.comment_settings import ActionCommentSettingsMixin


class TestPreprintActionFilters(ActionFilterMixin):

    @pytest.fixture()
    def preprint(self, all_actions):
        return all_actions[0].target

    @pytest.fixture(params=[True, False], ids=['moderator', 'node_admin'])
    def user(self, request, preprint):
        user = AuthUserFactory()
        if request.param:
            user.groups.add(GroupHelper(preprint.provider).get_group('moderator'))
        else:
            preprint.node.add_contributor(user, permissions=[osf_permissions.READ, osf_permissions.WRITE, osf_permissions.ADMIN])
        return user

    @pytest.fixture()
    def expected_actions(self, preprint, all_actions):
        return [r for r in all_actions if r.target_id == preprint.id]

    @pytest.fixture()
    def url(self, preprint):
        return '/{}preprints/{}/actions/'.format(API_BASE, preprint._id)

    def test_unauthorized_user(self, app, url):
        res = app.get(url, expect_errors=True)
        assert res.status_code == 401

        user = AuthUserFactory()
        res = app.get(url, auth=user.auth, expect_errors=True)
        assert res.status_code == 403


class TestActionSettings(ActionCommentSettingsMixin):
    @pytest.fixture()
    def url(self, preprint):
        return '/{}preprints/{}/actions/'.format(API_BASE, preprint._id)

api_tests/preprints/views/test_preprint_citations.py
# -*- coding: utf-8 -*-
from api.base.settings.defaults import API_BASE
from api.citations.utils import display_absolute_url
from nose.tools import *  # flake8: noqa
from osf_tests.factories import AuthUserFactory, PreprintFactory
from tests.base import ApiTestCase
from datetime import datetime


class PreprintCitationsMixin(object):

	def setUp(self):
		super(PreprintCitationsMixin, self).setUp()
		self.admin_contributor = AuthUserFactory()
		self.published_preprint = PreprintFactory(creator=self.admin_contributor)
		self.unpublished_preprint = PreprintFactory(creator=self.admin_contributor, is_published=False)

	def test_unauthenticated_can_view_published_preprint_citations(self):
		res = self.app.get(self.published_preprint_url)
		assert_equal(res.status_code, 200)

	def test_unauthenticated_cannot_view_unpublished_preprint_citations(self):
		res = self.app.get(self.unpublished_preprint_url, expect_errors=True)
		assert_equal(res.status_code, 401)

	def test_preprint_citations_are_read_only(self):
		post_res = self.app.post_json_api(self.published_preprint_url, {}, auth=self.admin_contributor.auth, expect_errors=True)
		assert_equal(post_res.status_code, 405)
		put_res = self.app.put_json_api(self.published_preprint_url, {}, auth=self.admin_contributor.auth, expect_errors=True)
		assert_equal(put_res.status_code, 405)
		delete_res = self.app.delete_json_api(self.published_preprint_url, auth=self.admin_contributor.auth, expect_errors=True)
		assert_equal(delete_res.status_code, 405)


class TestPreprintCitations(PreprintCitationsMixin, ApiTestCase):

	def setUp(self):
		super(TestPreprintCitations, self).setUp()
		self.published_preprint_url = '/{}preprints/{}/citation/'.format(API_BASE, self.published_preprint._id)
		self.unpublished_preprint_url = '/{}preprints/{}/citation/'.format(API_BASE, self.unpublished_preprint._id)

	def test_citation_publisher_is_preprint_provider(self):
		res = self.app.get(self.published_preprint_url)
		assert_equal(res.status_code, 200)
		assert_equal(res.json['data']['attributes']['publisher'], self.published_preprint.provider.name)

	def test_citation_url_is_preprint_url_not_project(self):
		res = self.app.get(self.published_preprint_url)
		assert_equal(res.status_code, 200)
		assert_equal(res.json['data']['links']['self'], display_absolute_url(self.published_preprint))


class TestPreprintCitationContent(PreprintCitationsMixin, ApiTestCase):

	def setUp(self):
		super(TestPreprintCitationContent, self).setUp()
		self.published_preprint_url = '/{}preprints/{}/citation/apa/'.format(API_BASE, self.published_preprint._id)
		self.unpublished_preprint_url = '/{}preprints/{}/citation/apa/'.format(API_BASE, self.unpublished_preprint._id)

	def test_citation_contains_correct_date(self):
		res = self.app.get(self.published_preprint_url)
		assert_equal(res.status_code, 200)
		expected_date = self.published_preprint.node.logs.latest().date.strftime('%Y, %B %-d')
		assert_true(expected_date in res.json['data']['attributes']['citation'])

		self.published_preprint.original_publication_date = datetime(2017, 12, 24)
		self.published_preprint.save()

		res = self.app.get(self.published_preprint_url)
		assert_equal(res.status_code, 200)
		expected_date = self.published_preprint.original_publication_date.strftime('%Y, %B %-d')
		assert_true(expected_date in res.json['data']['attributes']['citation'])

website/preprints/views.py
# -*- coding: utf-8 -*-
from framework.flask import redirect  # VOL-aware redirect

def preprint_landing_page(**kwargs):
    return {}


def preprint_redirect(**kwargs):
    return redirect('/preprints/')

admin/templates/preprints/preprint.html
{% extends 'base.html' %}
{% load static %}
{% load user_extras %}
{% load node_extras %}
{% block title %}
    <title>Preprint</title>
{% endblock title %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <a href="{% url 'preprints:search' %}"
                   class="btn btn-primary col-md-1">
                    <i class="fa fa-search"></i>
                </a>
                    {% if perms.osf.delete_preprintservice %}
                    {% if not serialized_preprint.node.deleted %}
                    <span class="col-md-2">
                        <a href="{% url 'nodes:remove' guid=serialized_preprint.node.id %}"
                           data-toggle="modal" data-target="#deleteModal"
                           class="btn btn-danger">
                            Delete Preprint Node
                        </a>
                        </span>
                        <div class="modal" id="deleteModal">
                            <div class="modal-dialog">
                                <div class="modal-content"></div>
                                 Data from above link
                            </div>
                        </div>
                    {% else %}
                        <span class="col-md-2">
                        <form method="post" action="{% url 'nodes:restore' guid=serialized_preprint.node.id %}">
                            {% csrf_token %}
                            <input class="btn btn-success" type="submit"
                                   value="Restore Preprint Node" />
                        </form>
                    </span>
                {% endif %}
                {% endif %}
            <span class="col-md-2">
                <a href="{% url 'preprints:reindex-share-preprint' guid=serialized_preprint.id %}"
                   data-toggle="modal" data-target="#confirmReindexSharePreprint"
                   class="btn btn-default">
                    SHARE Reindex
                </a>
            </span>
            <div class="modal" id="confirmReindexSharePreprint">
                <div class="modal-dialog">
                    <div class="modal-content"></div>
                    {# Data from above link #}
                </div>
            </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h3>Preprint Details</h3>
                <p>To remove contributors and perform other operations, <a href="{{ serialized_preprint.node.id | reverse_node }}">visit the associated node detail page</a>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Field</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>GUID</td>
                        <td>{{ serialized_preprint.id }}</td>
                    </tr>
                    <tr>
                        <td>Title</td>
                        <td>{{ serialized_preprint.node.title }}</td>
                    </tr>
                    <tr>
                        <td>Node</td>
                        <td>
                            <a href="{{ serialized_preprint.node.id | reverse_node }}">{{ serialized_preprint.node.id }}</a>
                        </td>
                    </tr>
                    <tr>
                        <td>Public</td>
                        <td>{{ serialized_preprint.node.is_public }}</td>
                    </tr>
                    <tr>
                        <td>Provider</td>
                        <td>
                            {{ serialized_preprint.provider.name }}
                            {% if perms.osf.change_preprintservice %}
                            <span class="provider_form_link" style="margin-left: 100px;">
                                <a class="btn btn-link" role="button" data-toggle="collapse" href="#collapseChangeProvider">
                                    Change prepint provider
                                </a>
                                <div class="collapse" id="collapseChangeProvider">
                                    <div class="well">
                                        <form action="" method="post">
                                            {% csrf_token %}
                                            {{ change_provider_form.as_p }}
                                            <input class="btn-btn-primary" type="submit" value="Submit" />
                                        </form>
                                    </div>
                                </div>
                            </span>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Subjects</td>
                        <td>
                            <ul>
                                {%  for subject in serialized_preprint.subjects %}
                                <li>{{ subject.text }}</li>
                                {%  endfor %}
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td>Date Created</td>
                        <td>{{ serialized_preprint.date_created }} UTC</td>
                    </tr>
                    <tr>
                        <td>Date Modified</td>
                        <td>{{ serialized_preprint.date_created }} UTC</td>
                    </tr>
                    <tr>
                        <td>Published</td>
                        <td>{{ serialized_preprint.is_published }}</td>
                    </tr>
                    {%  if serialized_preprint.is_published %}
                    <tr>
                        <td>Date Published</td>
                        <td>{{ serialized_preprint.date_published }} UTC</td>
                    </tr>
                    {%  endif %}

                    <tr>
                        <td>Creator</td>
                        <td>
                             <a href="{{ serialized_preprint.node.creator | reverse_user }}">
                                {{ serialized_preprint.node.creator }}
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>Contributors</td>
                        <td>
                            <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <td>User id</td>
                                    <td>Name</td>
                                    <td>Permissions</td>
                                </tr>
                            </thead>
                            <tbody>
                            {% for user in serialized_preprint.node.contributors %}
                                <tr>
                                    <td>
                                        <a href="{{ user.id | reverse_user }}">
                                            {{ user.id }}
                                        </a>
                                    </td>
                                    <td>{{ user.name }}</td>
                                    <td>{{ user.permission|capfirst }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

admin/templates/preprints/reindex_preprint_share.html
<form class="well" method="post" action="{% url 'preprints:reindex-share-preprint' guid=guid %}">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Are you sure you want to reindex this preprint (SHARE)? {{ guid }}</h3>
    </div>
    {% csrf_token %}
    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Confirm" />
        <button type="button" class="btn btn-default" data-dismiss="modal">
            Cancel
        </button>
    </div>
</form>

admin/templates/preprints/search.html
{% extends 'base.html' %}
{% load static %}
{#{% load node_extras %}#}
{% block title %}
    <title>Preprint Search</title>
{% endblock title %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <form action="{% url 'preprints:search' %}" method="post">
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger">{{ form.errors }}</div>
                {% endif %}
                <div class="form-group">
                    <label for="guid">Preprint GUID:</label>
                    {{ form.guid }}
                </div>
                <input type="submit" class="btn btn-primary" value="Submit" />
            </form>
        </div>
    </div>
{% endblock content %}