admin/nodes/urls.py
from django.conf.urls import url
from admin.nodes import views

app_name = 'admin'

urlpatterns = [
    url(r'^$', views.NodeFormView.as_view(),
        name='search'),
    url(r'^flagged_spam$', views.NodeFlaggedSpamList.as_view(),
        name='flagged-spam'),
    url(r'^known_spam$', views.NodeKnownSpamList.as_view(),
        name='known-spam'),
    url(r'^known_ham$', views.NodeKnownHamList.as_view(),
        name='known-ham'),
    url(r'^(?P<guid>[a-z0-9]+)/$', views.NodeView.as_view(),
        name='node'),
    url(r'^(?P<guid>[a-z0-9]+)/logs/$', views.AdminNodeLogView.as_view(),
        name='node-logs'),
    url(r'^registration_list/$', views.RegistrationListView.as_view(),
        name='registrations'),
    url(r'^(?P<guid>[a-z0-9]+)/update_embargo/$',
        views.RegistrationUpdateEmbargoView.as_view(), name='update_embargo'),
    url(r'^(?P<guid>[a-z0-9]+)/remove/$', views.NodeDeleteView.as_view(),
        name='remove'),
    url(r'^(?P<guid>[a-z0-9]+)/restore/$', views.NodeDeleteView.as_view(),
        name='restore'),
    url(r'^(?P<guid>[a-z0-9]+)/confirm_spam/$', views.NodeConfirmSpamView.as_view(),
        name='confirm-spam'),
    url(r'^(?P<guid>[a-z0-9]+)/confirm_ham/$', views.NodeConfirmHamView.as_view(),
        name='confirm-ham'),
    url(r'^(?P<guid>[a-z0-9]+)/reindex_share_node/$', views.NodeReindexShare.as_view(),
        name='reindex-share-node'),
    url(r'^(?P<guid>[a-z0-9]+)/reindex_elastic_node/$', views.NodeReindexElastic.as_view(),
        name='reindex-elastic-node'),
    url(r'^(?P<node_id>[a-z0-9]+)/remove_user/(?P<user_id>[a-z0-9]+)/$',
        views.NodeRemoveContributorView.as_view(), name='remove_user'),
]

api/base/urls.py
from django.conf import settings as drf_settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from . import views
from . import settings
from . import versioning

default_version = versioning.decimal_version_to_url_path(settings.REST_FRAMEWORK['DEFAULT_VERSION'])

# Please keep URLs alphabetized for auto-generated documentation
urlpatterns = [
    url('^(?P<version>(v2))/',
        include(
            [
                url(r'^$', views.root, name='root'),
                url(r'^status/', views.status_check, name='status_check'),
                url(r'^actions/', include('api.actions.urls', namespace='actions')),
                url(r'^addons/', include('api.addons.urls', namespace='addons')),
                url(r'^applications/', include('api.applications.urls', namespace='applications')),
                url(r'^citations/', include('api.citations.urls', namespace='citations')),
                url(r'^collections/', include('api.collections.urls', namespace='collections')),
                url(r'^comments/', include('api.comments.urls', namespace='comments')),
                url(r'^docs/', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version}),
                url(r'^files/', include('api.files.urls', namespace='files')),
                url(r'^guids/', include('api.guids.urls', namespace='guids')),
                url(r'^identifiers/', include('api.identifiers.urls', namespace='identifiers')),
                url(r'^institutions/', include('api.institutions.urls', namespace='institutions')),
                url(r'^licenses/', include('api.licenses.urls', namespace='licenses')),
                url(r'^logs/', include('api.logs.urls', namespace='logs')),
                url(r'^metaschemas/', include('api.metaschemas.urls', namespace='metaschemas')),
                url(r'^nodes/', include('api.nodes.urls', namespace='nodes')),
                url(r'^preprints/', include('api.preprints.urls', namespace='preprints')),
                url(r'^preprint_providers/', include('api.preprint_providers.urls', namespace='preprint_providers')),
                url(r'^registrations/', include('api.registrations.urls', namespace='registrations')),
                url(r'^search/', include('api.search.urls', namespace='search')),
                url(r'^taxonomies/', include('api.taxonomies.urls', namespace='taxonomies')),
                url(r'^test/', include('api.test.urls', namespace='test')),
                url(r'^tokens/', include('api.tokens.urls', namespace='tokens')),
                url(r'^users/', include('api.users.urls', namespace='users')),
                url(r'^view_only_links/', include('api.view_only_links.urls', namespace='view-only-links')),
                url(r'^wikis/', include('api.wikis.urls', namespace='wikis')),
            ],
        )
        ),
    url(r'^$', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version})
]


urlpatterns += static('/static/', document_root=drf_settings.STATIC_ROOT)

handler404 = views.error_404

api/nodes/urls.py
from django.conf.urls import url

from api.nodes import views

app_name = 'osf'

urlpatterns = [
    # Examples:
    # url(r'^$', 'api.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.NodeList.as_view(), name=views.NodeList.view_name),
    url(r'^(?P<node_id>\w+)/$', views.NodeDetail.as_view(), name=views.NodeDetail.view_name),
    url(r'^(?P<node_id>\w+)/addons/$', views.NodeAddonList.as_view(), name=views.NodeAddonList.view_name),
    url(r'^(?P<node_id>\w+)/addons/(?P<provider>\w+)/$', views.NodeAddonDetail.as_view(), name=views.NodeAddonDetail.view_name),
    url(r'^(?P<node_id>\w+)/addons/(?P<provider>\w+)/folders/$', views.NodeAddonFolderList.as_view(), name=views.NodeAddonFolderList.view_name),
    url(r'^(?P<node_id>\w+)/children/$', views.NodeChildrenList.as_view(), name=views.NodeChildrenList.view_name),
    url(r'^(?P<node_id>\w+)/citation/$', views.NodeCitationDetail.as_view(), name=views.NodeCitationDetail.view_name),
    url(r'^(?P<node_id>\w+)/citation/(?P<style_id>[-\w]+)/$', views.NodeCitationStyleDetail.as_view(), name=views.NodeCitationStyleDetail.view_name),
    url(r'^(?P<node_id>\w+)/comments/$', views.NodeCommentsList.as_view(), name=views.NodeCommentsList.view_name),
    url(r'^(?P<node_id>\w+)/contributors/$', views.NodeContributorsList.as_view(), name=views.NodeContributorsList.view_name),
    url(r'^(?P<node_id>\w+)/contributors/(?P<user_id>\w+)/$', views.NodeContributorDetail.as_view(), name=views.NodeContributorDetail.view_name),
    url(r'^(?P<node_id>\w+)/draft_registrations/$', views.NodeDraftRegistrationsList.as_view(), name=views.NodeDraftRegistrationsList.view_name),
    url(r'^(?P<node_id>\w+)/draft_registrations/(?P<draft_id>\w+)/$', views.NodeDraftRegistrationDetail.as_view(), name=views.NodeDraftRegistrationDetail.view_name),
    url(r'^(?P<node_id>\w+)/files/$', views.NodeProvidersList.as_view(), name=views.NodeProvidersList.view_name),
    url(r'^(?P<node_id>\w+)/files/providers/(?P<provider>\w+)/?$', views.NodeProviderDetail.as_view(), name=views.NodeProviderDetail.view_name),
    url(r'^(?P<node_id>\w+)/files/(?P<provider>\w+)(?P<path>/(?:.*/)?)$', views.NodeFilesList.as_view(), name=views.NodeFilesList.view_name),
    url(r'^(?P<node_id>\w+)/files/(?P<provider>\w+)(?P<path>/.+[^/])$', views.NodeFileDetail.as_view(), name=views.NodeFileDetail.view_name),
    url(r'^(?P<node_id>\w+)/forks/$', views.NodeForksList.as_view(), name=views.NodeForksList.view_name),
    url(r'^(?P<node_id>\w+)/identifiers/$', views.NodeIdentifierList.as_view(), name=views.NodeIdentifierList.view_name),
    url(r'^(?P<node_id>\w+)/institutions/$', views.NodeInstitutionsList.as_view(), name=views.NodeInstitutionsList.view_name),
    url(r'^(?P<node_id>\w+)/linked_nodes/$', views.LinkedNodesList.as_view(), name=views.LinkedNodesList.view_name),
    url(r'^(?P<node_id>\w+)/linked_registrations/$', views.NodeLinkedRegistrationsList.as_view(), name=views.NodeLinkedRegistrationsList.view_name),
    url(r'^(?P<node_id>\w+)/logs/$', views.NodeLogList.as_view(), name=views.NodeLogList.view_name),
    url(r'^(?P<node_id>\w+)/node_links/$', views.NodeLinksList.as_view(), name=views.NodeLinksList.view_name),
    url(r'^(?P<node_id>\w+)/node_links/(?P<node_link_id>\w+)/', views.NodeLinksDetail.as_view(), name=views.NodeLinksDetail.view_name),
    url(r'^(?P<node_id>\w+)/preprints/$', views.NodePreprintsList.as_view(), name=views.NodePreprintsList.view_name),
    url(r'^(?P<node_id>\w+)/registrations/$', views.NodeRegistrationsList.as_view(), name=views.NodeRegistrationsList.view_name),
    url(r'^(?P<node_id>\w+)/relationships/institutions/$', views.NodeInstitutionsRelationship.as_view(), name=views.NodeInstitutionsRelationship.view_name),
    url(r'^(?P<node_id>\w+)/relationships/linked_nodes/$', views.NodeLinkedNodesRelationship.as_view(), name=views.NodeLinkedNodesRelationship.view_name),
    url(r'^(?P<node_id>\w+)/relationships/linked_registrations/$', views.NodeLinkedRegistrationsRelationship.as_view(), name=views.NodeLinkedRegistrationsRelationship.view_name),
    url(r'^(?P<node_id>\w+)/view_only_links/$', views.NodeViewOnlyLinksList.as_view(), name=views.NodeViewOnlyLinksList.view_name),
    url(r'^(?P<node_id>\w+)/view_only_links/(?P<link_id>\w+)/$', views.NodeViewOnlyLinkDetail.as_view(), name=views.NodeViewOnlyLinkDetail.view_name),
    url(r'^(?P<node_id>\w+)/wikis/$', views.NodeWikiList.as_view(), name=views.NodeWikiList.view_name),
]

api/search/urls.py
from django.conf.urls import url

from api.search import views

app_name = 'osf'

urlpatterns = [
    url(r'^$', views.Search.as_view(), name=views.Search.view_name),
    url(r'^components/$', views.SearchComponents.as_view(), name=views.SearchComponents.view_name),
    url(r'^files/$', views.SearchFiles.as_view(), name=views.SearchFiles.view_name),
    url(r'^projects/$', views.SearchProjects.as_view(), name=views.SearchProjects.view_name),
    url(r'^registrations/$', views.SearchRegistrations.as_view(), name=views.SearchRegistrations.view_name),
    url(r'^users/$', views.SearchUsers.as_view(), name=views.SearchUsers.view_name),
    url(r'^institutions/$', views.SearchInstitutions.as_view(), name=views.SearchInstitutions.view_name),

    # not currently supported by v1, but should be supported by v2
    # url(r'^nodes/$', views.SearchProjects.as_view(), name=views.SearchProjects.view_name),
]

api_tests/nodes/views/test_node_citations.py
import pytest

from api.base.settings.defaults import API_BASE
from framework.auth.core import Auth
from rest_framework import exceptions
from osf_tests.factories import (
    ProjectFactory,
    AuthUserFactory,
)

@pytest.fixture()
def admin_contributor():
    return AuthUserFactory()

@pytest.fixture()
def write_contrib():
    return AuthUserFactory()

@pytest.fixture()
def read_contrib():
    return AuthUserFactory()

@pytest.fixture()
def non_contrib():
    return AuthUserFactory()

@pytest.fixture()
def disabled_contrib():
    # disabled in the disable_user fixture so that they can be added as a contributor first
    return AuthUserFactory()

@pytest.fixture()
def public_project(admin_contributor):
    return ProjectFactory(creator=admin_contributor, is_public=True)

@pytest.fixture()
def private_project(admin_contributor, write_contrib, read_contrib, disabled_contrib):
    private_project = ProjectFactory(creator=admin_contributor)
    private_project.add_contributor(write_contrib, permissions=['read','write'], auth=Auth(admin_contributor))
    private_project.add_contributor(read_contrib, permissions=['read'], auth=Auth(admin_contributor))
    private_project.add_contributor(disabled_contrib, permissions=['read'], auth=Auth(admin_contributor))
    private_project.save()
    return private_project

@pytest.fixture()
def disable_user(disabled_contrib, private_project):
    # pass private_project so that account is disabled after private_project is setup
    disabled_contrib.disable_account()
    disabled_contrib.is_registered = False
    disabled_contrib.save()

@pytest.mark.django_db
class NodeCitationsMixin:

    def test_node_citations(self, app, admin_contributor, write_contrib, read_contrib, non_contrib, disabled_contrib, private_url, public_url):

    #   test_admin_can_view_private_project_citations
        res = app.get(private_url, auth=admin_contributor.auth)
        assert res.status_code == 200

    #   test_write_contrib_can_view_private_project_citations
        res = app.get(private_url, auth=write_contrib.auth)
        assert res.status_code == 200

    #   test_read_contrib_can_view_private_project_citations
        res = app.get(private_url, auth=read_contrib.auth)
        assert res.status_code == 200

    #   test_non_contrib_cannot_view_private_project_citations
        res = app.get(private_url, auth=non_contrib.auth, expect_errors=True)
        assert res.status_code == 403
        assert res.json['errors'][0]['detail'] == exceptions.PermissionDenied.default_detail

    #   test_unauthenticated_cannot_view_private_project_citations
        res = app.get(private_url, expect_errors=True)
        assert res.status_code == 401
        assert res.json['errors'][0]['detail'] == exceptions.NotAuthenticated.default_detail

    #   test_unauthenticated_can_view_public_project_citations
        res = app.get(public_url)
        assert res.status_code == 200

    #   test_citations_are_read_only
        post_res = app.post_json_api(public_url, {}, auth=admin_contributor.auth, expect_errors=True)
        assert post_res.status_code == 405
        put_res = app.put_json_api(public_url, {}, auth=admin_contributor.auth, expect_errors=True)
        assert put_res.status_code == 405
        delete_res = app.delete_json_api(public_url, auth=admin_contributor.auth, expect_errors=True)
        assert delete_res.status_code == 405

class TestNodeCitations(NodeCitationsMixin):
    @pytest.fixture()
    def public_url(self, public_project):
        return '/{}nodes/{}/citation/'.format(API_BASE, public_project._id)

    @pytest.fixture()
    def private_url(self, private_project):
        return '/{}nodes/{}/citation/'.format(API_BASE, private_project._id)


class TestNodeCitationsStyle(NodeCitationsMixin):
    @pytest.fixture()
    def public_url(self, public_project):
        return '/{}nodes/{}/citation/apa/'.format(API_BASE, public_project._id)

    @pytest.fixture()
    def private_url(self, private_project):
        return '/{}nodes/{}/citation/apa/'.format(API_BASE, private_project._id)

api_tests/nodes/views/test_node_institutions_list.py
import pytest

from tests.base import ApiTestCase
from osf_tests.factories import InstitutionFactory, NodeFactory, AuthUserFactory
from api.base.settings.defaults import API_BASE

@pytest.fixture()
def user():
    return AuthUserFactory()

@pytest.mark.django_db
class TestNodeInstitutionDetail:

    @pytest.fixture()
    def institution(self):
        return InstitutionFactory()

    @pytest.fixture()
    def node_one(self, institution):
        node_one = NodeFactory(is_public=True)
        node_one.affiliated_institutions.add(institution)
        node_one.save()
        return node_one

    @pytest.fixture()
    def node_two(self, user):
        return NodeFactory(creator=user)

    def test_node_institution_detail(self, app, user, institution, node_one, node_two,):

    #   test_return_institution
        url = '/{0}nodes/{1}/institutions/'.format(API_BASE, node_one._id)
        res = app.get(url)

        assert res.status_code == 200
        assert res.json['data'][0]['attributes']['name'] == institution.name
        assert res.json['data'][0]['id'] == institution._id

    #   test_return_no_institution
        url = '/{0}nodes/{1}/institution/'.format(API_BASE, node_two._id)
        res = app.get(
                url, auth=user.auth,
                expect_errors=True
        )

        assert res.status_code == 404

admin/templates/nodes/confirm_ham.html
<form class="well" method="post" action="{% url 'nodes:confirm-ham' guid=guid %}">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Are you sure this node is <strong>not</strong> spam? {{ guid }}</h3>
    </div>
    {% csrf_token %}
    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Confirm" />
        <button type="button" class="btn btn-default" data-dismiss="modal">
            Cancel
        </button>
    </div>
</form>

admin/templates/nodes/confirm_spam.html
<form class="well" method="post" action="{% url 'nodes:confirm-spam' guid=guid %}">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Are you sure this node is spam? {{ guid }}</h3>
    </div>
    {% csrf_token %}
    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Confirm" />
        <button type="button" class="btn btn-default" data-dismiss="modal">
            Cancel
        </button>
    </div>
</form>

admin/templates/nodes/flagged_spam_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Flagged Spam Nodes</title>
{% endblock title %}
{% block content %}
  {% url 'nodes:flagged-spam' as form_action %}
  {% include 'nodes/node_list.html' with form_action=form_action show_title=True%}
{% endblock content %}

admin/templates/nodes/known_spam_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Known Spam Nodes</title>
{% endblock title %}
{% block content %}
  {% include 'nodes/node_list.html' %}
{% endblock content %}

admin/templates/nodes/node_list.html
{% load node_extras %}
{% include "util/pagination.html" with items=page status=status %}
{% if form_action %}
<form action={{form_action}} method="POST">
{% endif %}
<table class="table table-striped table-hover table-responsive">
    <thead>
        <tr>
            {% if form_action %}
            <th>
                <input type="checkbox" onclick="toggle(this)">
                <script language="javascript">
                    function toggle(source) {
                        var checkboxes = document.getElementsByClassName('selection');
                        for (var i in checkboxes) {
                            checkboxes[i].checked = source.checked;
                        }
                    }
                </script>
            </th>
            {% endif %}
            <th>GUID</th>
            {% if show_title %}
            <th>
                Title
            </th>
            {% endif %}
            <th>Parent</th>
            <th>Root</th>
            <th>Date created</th>
            <th>Public</th>
            <th>Withdrawn</th>
            <th>Embargo</th>
            <th>Contributors</th>
        </tr>
    </thead>
    <tbody>
        {% for node in nodes %}
        <tr>
            {% if form_action %}
            <td>
                <input name="{{node.id}}" class="selection" type="checkbox"/>
            </td>
            {% endif %}
            <td>
                <a href="{{ node.id | reverse_node }}"
                   class="btn btn-primary">
                    {{ node.id }}
                </a>
            </td>
            {% if show_title %}
            <td>
                {{node.title}}
            </td>
            {% endif %}
            <td>
                {% if not node.parent %}
                {{ node.parent }}
                {% else %}
                <a href="{{ node.parent | reverse_node }}">
                    {{ node.parent }}
                </a>
                {% endif %}
            </td>
            <td>
                {% if not node.root %}
                {{ node.root }}
                {% else %}
                <a href="{{ node.root | reverse_node }}">
                    {{ node.root }}
                </a>
                {% endif %}
            </td>
            <td>
                {{ node.date_created|date }}
            </td>
            <td>
                {{ node.public }}
            </td>
            <td>
                {{ node.retraction }}
            </td>
            <td>
                {{ node.embargo }}
            </td>
            <td>
                {% for user in node.contributors %}
                    <a href="{{ user.id | reverse_user }}">{{ user.username }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% if form_action and perms.osf.mark_spam %}
<button class="btn btn-warning" type="button" data-toggle="modal" data-target="#confirmSpamListModal">
    Confirm Spam
</button>
<div id="confirmSpamListModal" class="modal fade well" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">x</button>
                <h3>Are you sure the selected node(s) are spam?</h3>
            </div>
            <div class="modal-footer">
                <input class="btn btn-danger" type="submit" value="Confirm" />
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Cancel
                </button>
            </div>
        </div>
    </div>
</div>
{% csrf_token %}
</form>
{% endif %}

admin/templates/nodes/node_logs.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Node Logs</title>
{% endblock title %}
{% block content %}
    <div class="container-fluid">
        <table class="table table-striped table-hover table-responsive">
            <thead>
                <th>
                    Date
                </th>
                <th>
                    Action
                </th>
                <th>
                    User
                </th>
                <th>
                    Parameters
                </th>
            </thead>
            <tbody>
            {% for log, params in logs %}
                <tr>
                    <td>
                        {{ log.date }}
                    </td>
                    <td>
                        {{ log.action }}
                    </td>
                    <td>
                        {{ log.user }}
                    </td>
                    <td>
                        {% for key, value in params %}
                            <div>
                                <span><b>{{ key }}</b></span> : <span>{{ value }}</span>
                            </div>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            {% csrf_token %}
        </table>
    </div>
    {% include "util/pagination.html" with items=page status=status %}
{% endblock content %}

admin/templates/nodes/registration_list.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load node_extras %}

{% load static %}
{% block title %}
    <title>Registrations</title>
{% endblock title %}
{% block content %}
    <h2>List of Registrations</h2>
    {% include 'nodes/node_list.html' %}
{% endblock content %}

admin/templates/nodes/reindex_node_elastic.html
<form class="well" method="post" action="{% url 'nodes:reindex-elastic-node' guid=guid %}">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Are you sure you want to reindex this node (Elastic)? {{ guid }}</h3>
    </div>
    {% csrf_token %}
    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Confirm" />
        <button type="button" class="btn btn-default" data-dismiss="modal">
            Cancel
        </button>
    </div>
</form>

admin/templates/nodes/reindex_node_share.html
<form class="well" method="post" action="{% url 'nodes:reindex-share-node' guid=guid %}">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Are you sure you want to reindex this node (SHARE)? {{ guid }}</h3>
    </div>
    {% csrf_token %}
    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Confirm" />
        <button type="button" class="btn btn-default" data-dismiss="modal">
            Cancel
        </button>
    </div>
</form>

admin/templates/nodes/remove_contributor.html
<form class="well" method="post"
      action="{% url 'nodes:remove_user' node_id=node_id user_id=user.id %}">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Removing contributor: {{ user.name }}</h3>
    </div>
    <div class="modal-body">
        User will be removed. Currently only
        an admin on the project will be able to
        add them back.
        {% csrf_token %}
    </div>
    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Confirm" />
        <button type="button" class="btn btn-default"
                data-dismiss="modal">
            Cancel
        </button>
    </div>
</form>

admin/templates/nodes/remove_node.html
<form class="well" method="post" action="{% url 'nodes:remove' guid=guid %}">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Are you sure you want to delete this node? {{ guid }}</h3>
    </div>
    <div class="modal-body">
        This action will be reversible after the fact.
        {% csrf_token %}
    </div>
    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Confirm" />
        <button type="button" class="btn btn-default"
                data-dismiss="modal">
            Cancel
        </button>
    </div>
</form>

admin/templates/nodes/search.html
{% extends 'base.html' %}
{% load static %}
{% load node_extras %}
{% block title %}
    <title>Node Search</title>
{% endblock title %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <form action="{% url 'nodes:search' %}" method="post">
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger">{{ form.errors }}</div>
                {% endif %}
                <div class="form-group">
                    <label for="guid">Node GUID:</label>
                    {{ form.guid }}
                </div>
                <input type="submit" class="btn btn-primary" value="Submit" />
            </form>
        </div>
    </div>
{% endblock content %}