admin/base/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from settings import ADMIN_BASE

from . import views

base_pattern = '^{}'.format(ADMIN_BASE)

urlpatterns = [
    ### ADMIN ###
    url(
        base_pattern,
        include([
            url(r'^$', views.home, name='home'),
            url(r'^admin/', admin.site.urls),
            url(r'^spam/', include('admin.spam.urls', namespace='spam')),
            url(r'^institutions/', include('admin.institutions.urls', namespace='institutions')),
            url(r'^preprint_providers/', include('admin.preprint_providers.urls', namespace='preprint_providers')),
            url(r'^account/', include('admin.common_auth.urls', namespace='auth')),
            url(r'^password/', include('password_reset.urls')),
            url(r'^nodes/', include('admin.nodes.urls', namespace='nodes')),
            url(r'^preprints/', include('admin.preprints.urls', namespace='preprints')),
            url(r'^subjects/', include('admin.subjects.urls', namespace='subjects')),
            url(r'^users/', include('admin.users.urls', namespace='users')),
            url(r'^meetings/', include('admin.meetings.urls',
                                       namespace='meetings')),
            url(r'^project/', include('admin.pre_reg.urls', namespace='pre_reg')),
            url(r'^metrics/', include('admin.metrics.urls',
                                      namespace='metrics')),
            url(r'^desk/', include('admin.desk.urls',
                                   namespace='desk')),
        ]),
    ),
]

admin.site.site_header = 'OSF-Admin administration'

admin/metrics/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as login

from . import views

app_name = 'admin'

urlpatterns = [
    url(r'^$', login(views.MetricsView.as_view()), name='metrics'),
]

admin/nodes/urls.py
from django.conf.urls import url
from admin.nodes import views

app_name = 'admin'

urlpatterns = [
    url(r'^$', views.NodeFormView.as_view(),
        name='search'),
    url(r'^flagged_spam$', views.NodeFlaggedSpamList.as_view(),
        name='flagged-spam'),
    url(r'^known_spam$', views.NodeKnownSpamList.as_view(),
        name='known-spam'),
    url(r'^known_ham$', views.NodeKnownHamList.as_view(),
        name='known-ham'),
    url(r'^(?P<guid>[a-z0-9]+)/$', views.NodeView.as_view(),
        name='node'),
    url(r'^(?P<guid>[a-z0-9]+)/logs/$', views.AdminNodeLogView.as_view(),
        name='node-logs'),
    url(r'^registration_list/$', views.RegistrationListView.as_view(),
        name='registrations'),
    url(r'^(?P<guid>[a-z0-9]+)/update_embargo/$',
        views.RegistrationUpdateEmbargoView.as_view(), name='update_embargo'),
    url(r'^(?P<guid>[a-z0-9]+)/remove/$', views.NodeDeleteView.as_view(),
        name='remove'),
    url(r'^(?P<guid>[a-z0-9]+)/restore/$', views.NodeDeleteView.as_view(),
        name='restore'),
    url(r'^(?P<guid>[a-z0-9]+)/confirm_spam/$', views.NodeConfirmSpamView.as_view(),
        name='confirm-spam'),
    url(r'^(?P<guid>[a-z0-9]+)/confirm_ham/$', views.NodeConfirmHamView.as_view(),
        name='confirm-ham'),
    url(r'^(?P<guid>[a-z0-9]+)/reindex_share_node/$', views.NodeReindexShare.as_view(),
        name='reindex-share-node'),
    url(r'^(?P<guid>[a-z0-9]+)/reindex_elastic_node/$', views.NodeReindexElastic.as_view(),
        name='reindex-elastic-node'),
    url(r'^(?P<node_id>[a-z0-9]+)/remove_user/(?P<user_id>[a-z0-9]+)/$',
        views.NodeRemoveContributorView.as_view(), name='remove_user'),
]

admin/pre_reg/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as login

from admin.pre_reg import views

app_name = 'admin'

urlpatterns = [
    url(r'^$', views.DraftListView.as_view(), name='prereg'),
    url(r'^checkout_checkup/$', views.CheckoutCheckupView.as_view(), name='checkout_checkup'),
    url(
        r'^drafts/(?P<draft_pk>[0-9a-z]+)/$',
        views.DraftDetailView.as_view(),
        name='view_draft'
    ),
    url(
        r'^drafts/(?P<draft_pk>[0-9a-z]+)/update/$',
        views.DraftFormView.as_view(),
        name='update_draft'
    ),
    url(
        r'^drafts/(?P<draft_pk>[0-9a-z]+)/comment/$',
        views.CommentUpdateView.as_view(),
        name='comment'
    ),
    url(
        r'^(?P<node_id>[a-zA-Z0-9]{5})/files/(?P<provider>.+?)/(?P<file_id>.+)/?',
        login(views.view_file),
        name='view_file'
    )
]

admin/spam/urls.py
from django.conf.urls import url

from . import views

app_name = 'admin'

urlpatterns = [
    url(r'^$', views.SpamList.as_view(), name='spam'),
    url(
        r'^(?P<spam_id>[a-z0-9]+)/$',
        views.SpamDetail.as_view(),
        name='detail'
    ),
    url(
        r'^(?P<spam_id>[a-z0-9]+)/email/$',
        views.EmailView.as_view(),
        name='email'
    ),
    url(
        r'^user/(?P<user_id>[a-z0-9]+)/$',
        views.UserSpamList.as_view(),
        name='user_spam'
    ),
]

api/base/urls.py
from django.conf import settings as drf_settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from . import views
from . import settings
from . import versioning

default_version = versioning.decimal_version_to_url_path(settings.REST_FRAMEWORK['DEFAULT_VERSION'])

# Please keep URLs alphabetized for auto-generated documentation
urlpatterns = [
    url('^(?P<version>(v2))/',
        include(
            [
                url(r'^$', views.root, name='root'),
                url(r'^status/', views.status_check, name='status_check'),
                url(r'^actions/', include('api.actions.urls', namespace='actions')),
                url(r'^addons/', include('api.addons.urls', namespace='addons')),
                url(r'^applications/', include('api.applications.urls', namespace='applications')),
                url(r'^citations/', include('api.citations.urls', namespace='citations')),
                url(r'^collections/', include('api.collections.urls', namespace='collections')),
                url(r'^comments/', include('api.comments.urls', namespace='comments')),
                url(r'^docs/', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version}),
                url(r'^files/', include('api.files.urls', namespace='files')),
                url(r'^guids/', include('api.guids.urls', namespace='guids')),
                url(r'^identifiers/', include('api.identifiers.urls', namespace='identifiers')),
                url(r'^institutions/', include('api.institutions.urls', namespace='institutions')),
                url(r'^licenses/', include('api.licenses.urls', namespace='licenses')),
                url(r'^logs/', include('api.logs.urls', namespace='logs')),
                url(r'^metaschemas/', include('api.metaschemas.urls', namespace='metaschemas')),
                url(r'^nodes/', include('api.nodes.urls', namespace='nodes')),
                url(r'^preprints/', include('api.preprints.urls', namespace='preprints')),
                url(r'^preprint_providers/', include('api.preprint_providers.urls', namespace='preprint_providers')),
                url(r'^registrations/', include('api.registrations.urls', namespace='registrations')),
                url(r'^search/', include('api.search.urls', namespace='search')),
                url(r'^taxonomies/', include('api.taxonomies.urls', namespace='taxonomies')),
                url(r'^test/', include('api.test.urls', namespace='test')),
                url(r'^tokens/', include('api.tokens.urls', namespace='tokens')),
                url(r'^users/', include('api.users.urls', namespace='users')),
                url(r'^view_only_links/', include('api.view_only_links.urls', namespace='view-only-links')),
                url(r'^wikis/', include('api.wikis.urls', namespace='wikis')),
            ],
        )
        ),
    url(r'^$', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version})
]


urlpatterns += static('/static/', document_root=drf_settings.STATIC_ROOT)

handler404 = views.error_404

admin/base/forms.py
from django import forms
from django.core.validators import validate_email


class GuidForm(forms.Form):
    guid = forms.CharField(label='Guid', min_length=5, max_length=5,
                           required=True)  # TODO: Move max to 6 when needed


class MultiEmailField(forms.Field):
    def to_python(self, value):
        if not value:
            return []
        return [r.strip().lower() for r in value.split(',')]

    def validate(self, value):
        super(MultiEmailField, self).validate(value)
        for email in value:
            validate_email(email)


class ImportFileForm(forms.Form):
    file = forms.FileField()

admin/base/views.py
from __future__ import unicode_literals

from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render
from django.views.generic import FormView, DetailView
from django.views.defaults import page_not_found

from admin.base.forms import GuidForm
from admin.base.utils import osf_staff_check


@user_passes_test(osf_staff_check)
def home(request):
    context = {}
    return render(request, 'home.html', context)


class GuidFormView(FormView):
    form_class = GuidForm
    template_name = None
    object_type = None

    def __init__(self):
        self.guid = None
        super(GuidFormView, self).__init__()

    def get_context_data(self, **kwargs):
        kwargs.setdefault('view', self)
        kwargs.setdefault('form', self.get_form())
        return kwargs

    def form_valid(self, form):
        self.guid = form.cleaned_data.get('guid').strip()
        return super(GuidFormView, self).form_valid(form)

    @property
    def success_url(self):
        raise NotImplementedError


class GuidView(DetailView):
    def get(self, request, *args, **kwargs):
        try:
            return super(GuidView, self).get(request, *args, **kwargs)
        except AttributeError:
            return page_not_found(
                request,
                AttributeError(
                    '{} with id "{}" not found.'.format(
                        self.context_object_name.title(),
                        kwargs.get('guid')
                    )
                )
            )

admin/templates/base.html
{% load staticfiles %}
{% load render_bundle from webpack_loader %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    {% block title %}
      <title>OSF Admin | Dashboard</title>
    {% endblock %}

    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap -->
    <link href="{% static 'vendor/bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'vendor/bower_components/admin-lte/dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- AdminLTE Skins. -->
    <link href="{% static 'vendor/bower_components/admin-lte/dist/css/skins/skin-blue.min.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" />

    <link href="{% static 'vendor/bower_components/jquery-ui/themes/redmond/jquery-ui.css' %}" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{% static 'vendor/bower_components/raven-js/dist/raven.min.js' %}"></script>
    <script src="{% static 'vendor/bower_components/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'vendor/bower_components/jquery-ui/ui/minified/jquery-ui.min.js' %}"></script>

    {% block top_includes %}

    {% endblock %}
  </head>
  <body class="skin-blue sidebar-mini">
    <div class="wrapper">

      <!-- Main Header -->
      {% block header %}
      <header class="main-header">

        <!-- Logo -->
        <a href="{% url 'home' %}" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>O</b>SF</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>OSF</b>Admin</span>
        </a>
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">
              {% if user.is_authenticated %}
              <!-- User Account Menu -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <span class="hidden-xs">
                      Logged in as {{ request.user.get_username }}
                      <span class="caret"></span>
                  </span>
                </a>
                <ul class="dropdown-menu user-menu">
                    {%  if perms.osf.change_osfuser %}
                  <li>
                    <a href="{% url 'auth:register' %}">
                      Admin-User Registration
                    </a>
                  </li>
                    {% endif %}
                  <li>
                    <a href="{% url 'auth:desk' %}">
                      Desk information
                    </a>
                  </li>
                </ul>
              </li>
              <li>
                <a href="{% url 'auth:logout' %}" class="btn btn-danger btn-flat">Sign out</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>
        {% endblock %}
      </header>
      {% block sidebar %}
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar Menu -->
          <ul class="sidebar-menu">
            <li class="header">Menu</li>
            {% if perms.osf.view_node %}
                <li><a role="button" data-toggle="collapse" href="#collapseNodes">
                  <i class='fa fa-caret-down'></i> OSF Nodes
              </a></li>
            <li>
                <div class="collapse" id="collapseNodes">
                    <ul class="sidebar-menu sidebar-menu-inner">
                        <li><a href="{% url 'nodes:search' %}"><i class='fa fa-link'></i><span> OSF Nodes</span> </a></li>
                        <li><a href="{% url 'nodes:flagged-spam' %}"><i class="fa fa-exclamation-triangle"></i><span> Flagged Spam</span> </a></li>
                        <li><a href="{% url 'nodes:known-spam' %}"><i class="fa fa-cutlery"></i><span> Known Spam</span> </a></li>
                        <li><a href="{% url 'nodes:known-ham' %}"><i class="fa fa-star"></i><span> Known Ham</span> </a></li>
                    </ul>
                </div>
            </li>
            {% endif %}
            {% if perms.osf.view_preprintservice %}
            <li><a href="{% url 'preprints:search' %}"><i class='fa fa-link'></i><span>Preprints</span> </a></li>
            {% endif %}
          {% if perms.osf.view_osfuser %}
              <li><a role="button" data-toggle="collapse" href="#collapseUsers">
                  <i class='fa fa-caret-down'></i> OSF Users
              </a></li>
              <div class="collapse" id="collapseUsers">
                  <ul class="sidebar-menu sidebar-menu-inner">
                      <li><a href="{% url 'users:search' %}"><i class='fa fa-link'></i><span>OSF Users</span> </a></li>
                      <li><a href="{% url 'users:flagged-spam' %}"><i class="fa fa-exclamation-triangle"></i><span> Flagged Spam</span> </a></li>
                      <li><a href="{% url 'users:known-spam' %}"><i class="fa fa-cutlery"></i><span> Known Spam</span> </a></li>
                      <li><a href="{% url 'users:known-ham' %}"><i class="fa fa-star"></i><span> Known Ham</span> </a></li>
                  </ul>
              </div>
          {% endif %}
          {% if perms.osf.view_spam %}
            <li><a href="{% url 'spam:spam' %}"><i class='fa fa-link'></i> <span>OSF Spam</span></a></li>
          {% endif %}
          {% if perms.osf.view_registration %}
            <li><a href="{% url 'nodes:registrations' %}"><i class='fa fa-link'></i> <span>OSF Registrations</span></a></li>
          {% endif %}
          {% if perms.osf.view_institution %}
              <li><a role="button" data-toggle="collapse" href="#collapseInstitutions">
                  <i class='fa fa-caret-down'></i> OSF Institutions
              </a></li>
              <div class="collapse" id="collapseInstitutions">
                  <ul class="sidebar-menu sidebar-menu-inner">
                      <li><a href="{% url 'institutions:list' %}"><i class='fa fa-link'></i><span> List</span> </a></li>
                      {% if perms.osf.change_institution %}
                      <li><a href="{% url 'institutions:create' %}"><i class='fa fa-link'></i><span> Create</span> </a></li>
                      {% endif %}
                  </ul>
              </div>
          {% endif %}
          {% if perms.osf.view_preprintprovider %}
              <li><a role="button" data-toggle="collapse" href="#collapsePreprintProviders">
                  <i class='fa fa-caret-down'></i> Preprint Providers
              </a></li>
              <div class="collapse" id="collapsePreprintProviders">
                  <ul class="sidebar-menu sidebar-menu-inner">
                      <li><a href="{% url 'preprint_providers:list' %}"><i class='fa fa-link'></i><span> List</span> </a></li>
                      {% if perms.osf.change_preprintprovider %}
                      <li><a href="{% url 'preprint_providers:create' %}"><i class='fa fa-link'></i><span> Create</span> </a></li>
                      {% endif %}
                  </ul>
              </div>
          {% endif %}
          {% if perms.osf.view_conference %}
            <li><a href="{% url 'meetings:list' %}"><i class='fa fa-link'></i> <span>OSF Meetings</span></a></li>
          {% endif %}
          {% if perms.osf.view_prereg %}
            <li><a href="{% url 'pre_reg:prereg' %}"><i class='fa fa-link'></i> <span>OSF Prereg</span></a></li>
            {% endif %}
          {% if perms.osf.view_metrics %}
            <li><a href="{% url 'metrics:metrics' %}"><i class='fa fa-link'></i> <span>OSF Metrics</span></a></li>
          {% endif %}
          {% if perms.osf.view_subject%}
            <li><a href="{% url 'subjects:list' %}"><i class='fa fa-link'></i> <span>OSF Subjects</span></a></li>
          {% endif %}
          </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
      </aside>
      {% endblock %}
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <!-- Main content -->
        <section class="content">
          {% block content %}
          <h1>
           Welcome to the OSF Admin Home Page
          </h1>
          <!-- Your Page Content Here -->
          {% endblock %}
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- Default to the left -->
        <strong>Copyright &copy; 2015-2016 <a href="http://www.osf.io">osf.io</a>.</strong> All rights reserved.
      </footer>

    </div><!-- ./wrapper -->

    <!-- Included JS -->
    {% render_bundle 'vendor' %}
    {% render_bundle 'admin-base-page' %}

    {% block bottom_js %}

    {% endblock %}

  </body>
</html>

{% if 'admin.osf.io' in request.META.HTTP_HOST and not '-admin.osf.io' in request.META.HTTP_HOST %}
  <style>
    .navbar { background-color: #bc493c !important;}
    .logo { background-color: #a53e35 !important;}
  </style>
{% endif %}

admin/templates/base_analytics.html
{% extends 'base.html' %}
{% load static %}

{% block top_includes %}
    <script>
        if ('{{ keen_ready }}' == 'True') {
            var keenProjectId = '{{ keen_project_id }}';
            var keenReadKey = '{{ keen_read_key }}';
        }
    </script>

    {% block top_analytics %}
    {% endblock top_analytics %}

{% endblock top_includes %}

{% block title %}
    <title>OSF Sales Analytics</title>
{% endblock title %}


{% block content %}

    {% block topmenu %}
        <a href="{% url 'sales_analytics:dashboard' %}" class="btn btn-primary">
            Analytics Dashboard
        </a>
    {% endblock topmenu %}

    {% block title_analytics %}

    {% endblock title_analytics %}

    {% block content_analytics %}

    {% endblock content_analytics %}

{% endblock content %}

admin/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1> Hello {{ user.get_username }}, </h1>
    <section class="content">
        <h3>Welcome to the OSF Admin Home Page</h3>
        <p> Use the menu on the left to access admin pages. </p>
        <div>
            {% if messages %}
            <ul class="login_page_messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
                </li>
            {% endfor %}
            </ul>
            {% endif %}
        </div>
    </section>
{% endblock %}

admin/templates/login.html
{% extends 'base.html' %}
{% load render_bundle from webpack_loader %}

{% block title %}
<title>OSFAdmin | Log in</title>
{% endblock %}

<!-- hide navbar, sidebar, and User account menu -->
{% block navbar %}
{% endblock %}
{% block sidebar %}
{% endblock %}

{% block content %}

<div class="login-page">
    <div class="login-box">
        <div class="login-logo">
            <b>OSF</b>Admin</a>
        </div><!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Sign in to start your session</p>
            <form action="" method="post">
                {% csrf_token %}
                {% if form.non_field_errors %}
                <ul>
                {% for error in form.non_field_errors %}
                <li class="errorclass">{{ error }}</li>
                {% endfor %}
                </ul>
                {% endif %}
                <div class="form-group">
                    <label for="username">Email:</label>
                    <p>{{ form.email }}</p>
                    {% if form.email.errors %}<span class="text-danger"> {{ form.email.errors }}</span>{% endif %}
                </div>
                <div class="form-group">
                    <label for="username">Password:</label>
                    <p>{{ form.password }}</p>
                    {% if form.password.errors %}<span class="text-danger"> {{ form.password.errors }}</span>{% endif %}
                </div>
                <div class="row">
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div><!-- /.col -->
                </div>
                <div>
                    {% if messages %}
                        <ul class="register_page_messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
                            </li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </form>
        </div><!-- /.login-box-body -->
      <br><!-- refactor  -->
    </div><!-- /.login-box -->
</div>
{% endblock %}

admin/templates/password_change_done.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block content %}
    {{ title }}
{% endblock %}

admin/templates/register.html
{% extends 'base.html' %}
{% load render_bundle from webpack_loader %}
{% load staticfiles %}

{% block content %}
<div class="register-box">
    <div class="register-box-body">
        <h4>Add or Update an OSF Admin user</h4>
        <div>
          {% if messages %}
            <ul class="login_page_messages">
              {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        </div>
        <form action="" method="post">
            {% csrf_token %}

            {% if form.non_field_errors %}
            <ul>
            {% for error in form.non_field_errors %}
            <li class="errorclass">{{ error }}</li>
            {% endfor %}
            </ul>
            {% endif %}
            <div class="form-group">
                <label for="email">OSF ID:</label>
                <p>{{ form.osf_id }}</p>
                {% if form.osf_id.errors %}<span class="text-danger"> {{ form.osf_id.errors }}</span>{% endif %}
            </div>
            <div class="form-group">
                <h4><strong>Select Groups for Permissions</strong></h4>
                <p>Please select from the below options to choose which group of permissions this user will have.</p>
                <p><strong>metrics_only:</strong><br>User can only view metrics on the OSF Admin page</p>
                <p><strong>read_only</strong><br>User can view details of nodes, preprints, users, meetings, metrics, and spam, but cannot make changes</p>
                <p><strong>osf_admin</strong><br>User make changes to nodes, preprints, users, meetings, and mark spam</p>
                <p><strong>prereg_admin</strong><br>User can view, approve, and make changes to entries to the preregistration challenge</p>
                <p><strong>prereg_view</strong><br>User can view entries to the preregistration challenge, but not approve or make changes.</p>

                <p>{{ form.group_perms }}</p>
                {% if form.group_perms.errors %}<span class="text-danger"> {{ form.group_perms.errors }}</span>{% endif %}
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                </div><!-- /.col -->
            </div>
        </form>
    </div><!-- /.form-box -->
</div><!-- /.register-box -->
{% endblock %}